# Python_Challenge
error received:

Exception has occurred: FileNotFoundError
[Errno 2] No such file or directory: '..\\Pybank\\Resources\\budget_data.csv'
  File "C:\Users\ferna\Desktop\HOMEWORK\Python_Challenge\Pybank\main.py", line 13, in <module>
    with open(input_path) as csvfile:
